---
- name: Create .docker directory
  file:
    path: "{{ ansible_user_dir }}/.docker"
    state: directory
    mode: '0755'

- name: Configure Docker Compose CLI plugins directory
  copy:
    content: |
      {
      	"auths": {},
      	"cliPluginsExtraDirs": [
      		"/home/linuxbrew/.linuxbrew/lib/docker/cli-plugins"
      	]
      }
    dest: "{{ ansible_user_dir }}/.docker/config.json"
    mode: '0644'
