---
- name: Bootstrap WSL with Homebrew, modern tools, and Zsh
  hosts: localhost
  connection: local

  roles:
    - common
    - brew
    - docker
    - git
    - ssh
    - zsh
    - vscode
    - obsidian